### ISSUE TITLE
Nullpointer when shutting down with 3 nodes in the network

### ISSUE THREAD

**Issue by Dieter97** [SuperiorNiels/SystemY#4]
Exception in thread "main" java.lang.NullPointerException
	at Node.FileManager.shutdown(FileManager.java:272)
	at Node.Node.shutDown(Node.java:364)
	at Node.Node.bootstrap(Node.java:126)
	at Node.Node.<init>(Node.java:40)
	at Main.main(Main.java:12)

**Comment by Dieter97** [comment]
Fixed. Replicate should now work as it should!
